### ISSUE TITLE
Preventing Sync Loops

### ISSUE THREAD

**Issue by cliftonlabrum** [insidegui/NoteTaker#3]
Hey, I just wanted to say thank you for such a great Medium article and a super-helpful sample project. You really helped me a lot with this and I'm very grateful. 🙂

One quick question for you. I'm having an issue where I have a sync loop happening. It goes something like this:

1. I update a record in Realm.
2. The realm notification fires and it pushes the change to CloudKit
3. The CloudKit record changes and thus sends a subscription notification to my app.
4. My app sees the notification and updates Realm.

Fortunately it seems to stop after a single loop, but everything is happening twice.

I'm unclear on how you are preventing this in your app. Can you give me any pointers? 

Thanks again!

**Comment by insidegui** [comment]
You have to pass the notification token when you commit a write so that token doesn't get the notification: https://github.com/insidegui/NoteTaker/blob/7f58ddbc24cc92b0003ebf9cf810ff64cd3a9c54/NoteTakerCore/Source/NotesStorage.swift#L105

**Comment by cliftonlabrum** [comment]
Cool, thanks!

**Comment by cliftonlabrum** [comment]
Sorry to bother you about this again, but I'm still not quite getting it. :)

Let's say the following is the cycle of saving a record:

A) I change Realm object "Dog" and write it to the realm.
B) The change notification is fired and the record is pushed up to CloudKit.
C) CloudKit saves the record and sends a notification to all clients that "Dog" changed.
D) The client that just barely sent the change also gets the CloudKit notification and updates "Dog" again.
E) The cycle repeats.

In which step do you pass the token to not notify the Realm to update? What if I need the rest of my app to know about the change? Suppressing the notification would make my app not react to the change correctly.

Am I missing something?

**Comment by insidegui** [comment]
> The client that just barely sent the change also gets the CloudKit notification and updates "Dog" again.

The app that just sent the change to CloudKit should not be getting the notification, that's not the correct behavior. If you're seeing that in your app, there's either something wrong with your setup or a bug in CloudKit (in which case you should [file a radar](https://bugreport.apple.com))

> In which step do you pass the token to not notify the Realm to update?

When you call `Realm.commitWrite()` to persist a change caused by a CloudKit notification, in the `withoutNotifying:` parameter.

> Suppressing the notification would make my app not react to the change correctly.

The SyncEngine has its own notification token and that's the only one that should not be notified when the SyncEngine performs a change caused by a CloudKit notification. Other sync tokens in your app will get the notification normally.

**Comment by cliftonlabrum** [comment]
Thanks for your thorough reply. I think I figured it out.
